name: General AutoTag

on:
  push:
    paths:
    - VERSION
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jaliborc/action-general-autotag@1.0.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        source_file: "VERSION"
        extraction_regex: "^(\\d+\\.\\d+\\.\\d+)$"
        tag_format: "v{version}"
        tag_message: "Tagged by General AutoTag Github Action."
